# -*- coding: utf-8 -*-
"""Добавляет 3 темы B1 в data/extra_words.json (new_themes) + грамматику B1.
Идемпотентно: если темы уже есть — заменяет их."""
import json,os
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

B1=[
{'t':'Общество и среда','w':[
 ['de samenleving','общество'],['de maatschappij','общество, социум'],['de burger','гражданин'],
 ['de overheid','власти, государство'],['de gemeenschap','сообщество'],['de bevolking','население'],
 ['de inwoner','житель'],['de minderheid','меньшинство'],['de meerderheid','большинство'],
 ['de integratie','интеграция'],['inburgeren','интегрироваться (инбургеринг)'],['de nieuwkomer','вновь прибывший'],
 ['de vluchteling','беженец'],['de asielzoeker','лицо, ищущее убежища'],['het vooroordeel','предрассудок'],
 ['de discriminatie','дискриминация'],['de gelijkheid','равенство'],['de vrijheid','свобода'],
 ['de tolerantie','терпимость'],['de norm','норма'],['de waarde','ценность'],
 ['de gewoonte','обычай, привычка'],['de traditie','традиция'],['de cultuur','культура'],
 ['het respect','уважение'],['de verantwoordelijkheid','ответственность'],['het recht','право'],
 ['de plicht','обязанность'],['de wet','закон'],['verboden','запрещено'],
 ['toegestaan','разрешено'],['de regel','правило'],['de invloed','влияние'],
 ['de ontwikkeling','развитие'],['de verandering','изменение'],['de vooruitgang','прогресс'],
 ['het probleem','проблема'],['de oplossing','решение'],['de oorzaak','причина'],
 ['het gevolg','последствие'],['het milieu','окружающая среда'],['de natuur','природа'],
 ['de vervuiling','загрязнение'],['de uitstoot','выбросы'],['de opwarming','потепление'],
 ['het klimaat','климат'],['duurzaam','устойчивый, экологичный'],['het afval','отходы, мусор'],
 ['recyclen','перерабатывать'],['scheiden','сортировать (отходы)'],['besparen','экономить'],
 ['de energie','энергия'],['de zonnepaneel','солнечная панель'],['de windmolen','ветряк'],
 ['het openbaar vervoer','общественный транспорт'],['de fiets','велосипед'],['de uitstoot verminderen','сокращать выбросы'],
 ['het nieuws','новости'],['de media','СМИ'],['de krant','газета'],
 ['het artikel','статья'],['de bron','источник'],['betrouwbaar','надёжный, достоверный'],
 ['de mening','мнение'],['het standpunt','точка зрения'],['het argument','аргумент'],
 ['de discussie','дискуссия'],['het debat','дебаты'],['overtuigen','убеждать'],
 ['het bewijs','доказательство'],['de feiten','факты'],['eens zijn','быть согласным'],
 ['oneens zijn','быть несогласным'],['de politiek','политика'],['de politicus','политик'],
 ['de partij','партия'],['de verkiezing','выборы'],['stemmen','голосовать'],
 ['de regering','правительство'],['de minister','министр'],['de gemeente','муниципалитет'],
 ['de belasting','налог'],['de subsidie','субсидия'],['de begroting','бюджет'],
 ['het protest','протест'],['de staking','забастовка'],['demonstreren','демонстрировать'],
 ['de vrijwilliger','волонтёр'],['de armoede','бедность'],['de welvaart','благосостояние'],
 ['de solidariteit','солидарность'],['de eenzaamheid','одиночество'],['de veiligheid','безопасность'],
 ['de criminaliteit','преступность'],['de dader','преступник'],['het slachtoffer','жертва'],
 ['de rechter','судья'],['de rechtbank','суд'],['de straf','наказание'],
 ['de boete','штраф'],['schuldig','виновный'],['onschuldig','невиновный'],
]},
{'t':'Карьера','w':[
 ['de carrière','карьера'],['de loopbaan','карьера, трудовой путь'],['de ambitie','амбиция'],
 ['de vaardigheid','навык'],['de competentie','компетенция'],['de ervaring','опыт'],
 ['de kwalificatie','квалификация'],['het diploma','диплом'],['het certificaat','сертификат'],
 ['de opleiding','образование, курс'],['de stage','стажировка'],['de stagiair','стажёр'],
 ['de sollicitatie','отклик на вакансию'],['solliciteren','подавать заявку на работу'],['het sollicitatiegesprek','собеседование'],
 ['de vacature','вакансия'],['het cv','резюме'],['de motivatiebrief','мотивационное письмо'],
 ['de werkgever','работодатель'],['de werknemer','работник'],['de collega','коллега'],
 ['de leidinggevende','руководитель'],['de manager','менеджер'],['de afdeling','отдел'],
 ['het team','команда'],['de functie','должность'],['de taak','задача'],
 ['het contract','контракт'],['vast','постоянный (контракт)'],['tijdelijk','временный'],
 ['het salaris','зарплата'],['het loon','оклад, заработок'],['de toeslag','надбавка'],
 ['de bonus','премия'],['het minimumloon','минимальная зарплата'],['de arbeidsvoorwaarden','условия труда'],
 ['fulltime','полный день'],['parttime','неполный день'],['de werkdruk','рабочая нагрузка'],
 ['de deadline','дедлайн'],['de vergadering','совещание'],['het overleg','обсуждение'],
 ['de presentatie','презентация'],['het project','проект'],['de samenwerking','сотрудничество'],
 ['communiceren','общаться'],['overleggen','советоваться'],['de feedback','обратная связь'],
 ['het functioneringsgesprek','аттестационная беседа'],['de beoordeling','оценка'],['de promotie','повышение'],
 ['de bevordering','продвижение'],['het ontslag','увольнение'],['ontslaan','увольнять'],
 ['opzeggen','увольняться, расторгать'],['de opzegtermijn','срок уведомления'],['de proeftijd','испытательный срок'],
 ['de werkloosheid','безработица'],['werkloos','безработный'],['de uitkering','пособие'],
 ['het UWV','агентство по труду (UWV)'],['de zzp\'er','самозанятый'],['het bedrijf','компания'],
 ['de onderneming','предприятие'],['de ondernemer','предприниматель'],['de klant','клиент'],
 ['de omzet','оборот'],['de winst','прибыль'],['het verlies','убыток'],
 ['de investering','инвестиция'],['de concurrentie','конкуренция'],['de markt','рынок'],
 ['het aanbod','предложение'],['de vraag','спрос'],['de doelgroep','целевая аудитория'],
 ['de strategie','стратегия'],['het doel','цель'],['het resultaat','результат'],
 ['efficiënt','эффективный'],['flexibel','гибкий'],['betrouwbaar','надёжный'],
 ['zelfstandig','самостоятельный'],['gemotiveerd','мотивированный'],['stressbestendig','стрессоустойчивый'],
 ['de werkervaring','опыт работы'],['bijscholen','повышать квалификацию'],['de cursus','курс'],
 ['het netwerk','сеть контактов'],['netwerken','налаживать связи'],['de kans','шанс, возможность'],
 ['de uitdaging','вызов'],['de groei','рост'],['zich ontwikkelen','развиваться'],
 ['de balans','баланс'],['het thuiswerken','работа из дома'],['de reistijd','время в пути'],
 ['de verzekering','страховка'],['het pensioen','пенсия'],['de vakantiedagen','отпускные дни'],
]},
{'t':'Здоровье и инстанции','w':[
 ['de gezondheid','здоровье'],['de zorg','уход, забота'],['de gezondheidszorg','здравоохранение'],
 ['de huisarts','семейный врач'],['de specialist','специалист'],['het ziekenhuis','больница'],
 ['de afspraak','запись, приём'],['de verwijzing','направление'],['de diagnose','диагноз'],
 ['de behandeling','лечение'],['het onderzoek','обследование'],['de klacht','жалоба (на здоровье)'],
 ['het symptoom','симптом'],['de aandoening','заболевание'],['chronisch','хронический'],
 ['de pijn','боль'],['de ontsteking','воспаление'],['de bloeddruk','давление крови'],
 ['de allergie','аллергия'],['besmettelijk','заразный'],['de infectie','инфекция'],
 ['de operatie','операция'],['de ingreep','вмешательство'],['herstellen','выздоравливать'],
 ['het herstel','выздоровление'],['de revalidatie','реабилитация'],['de fysiotherapeut','физиотерапевт'],
 ['de psycholoog','психолог'],['de therapie','терапия'],['het recept','рецепт'],
 ['het medicijn','лекарство'],['de apotheek','аптека'],['de bijwerking','побочный эффект'],
 ['de dosis','доза'],['de verzekering','страховка'],['de zorgverzekering','медицинская страховка'],
 ['de premie','страховой взнос'],['het eigen risico','франшиза (собственный риск)'],['de vergoeding','возмещение'],
 ['de nota','счёт'],['declareren','подавать на возмещение'],['de aanvraag','заявление'],
 ['aanvragen','подавать заявку'],['het formulier','бланк, форма'],['invullen','заполнять'],
 ['ondertekenen','подписывать'],['de handtekening','подпись'],['de bijlage','приложение (документ)'],
 ['de instantie','инстанция, орган'],['het loket','окошко, стойка'],['de balie','стойка регистрации'],
 ['de ambtenaar','чиновник'],['de aanvrager','заявитель'],['de gemeente','муниципалитет'],
 ['de Belastingdienst','налоговая служба'],['de toeslag','пособие, надбавка'],['de huurtoeslag','пособие на аренду'],
 ['de zorgtoeslag','пособие на страховку'],['de kinderbijslag','детское пособие'],['de bijstand','социальное пособие'],
 ['de DigiD','ДиджиАй-Ди (цифровой ключ)'],['inloggen','входить (в аккаунт)'],['de brief','письмо'],
 ['de beschikking','официальное решение'],['het besluit','решение'],['bezwaar maken','подавать возражение'],
 ['het bezwaar','возражение'],['de termijn','срок'],['de deadline','крайний срок'],
 ['geldig','действительный'],['verlopen','просроченный'],['verlengen','продлевать'],
 ['de identiteitskaart','удостоверение личности'],['het paspoort','паспорт'],['de verblijfsvergunning','вид на жительство'],
 ['de vergunning','разрешение'],['de registratie','регистрация'],['inschrijven','регистрироваться'],
 ['uitschrijven','сниматься с учёта'],['het adres','адрес'],['de verhuizing','переезд'],
 ['doorgeven','сообщать, передавать'],['de wijziging','изменение'],['bevestigen','подтверждать'],
 ['de bevestiging','подтверждение'],['de ontvangst','получение'],['reageren','реагировать, отвечать'],
 ['de reactie','реакция, ответ'],['het contact','контакт'],['de klachtenprocedure','процедура жалоб'],
 ['de rechten','права'],['de plichten','обязанности'],['de begeleiding','сопровождение, поддержка'],
 ['de hulp','помощь'],['het advies','совет'],['adviseren','советовать'],
 ['de afspraak maken','записаться на приём'],['annuleren','отменять'],['verzetten','переносить (встречу)'],
]},
]

ex=json.load(open(ROOT+'/data/extra_words.json',encoding='utf-8'))
names={t['t'] for t in B1}
ex['new_themes']=[t for t in ex['new_themes'] if t['t'] not in names]+B1
json.dump(ex,open(ROOT+'/data/extra_words.json','w',encoding='utf-8'),ensure_ascii=False,indent=1)
tot=sum(len(t['w']) for t in B1)
print('B1 тем:',len(B1),' слов B1:',tot)
for t in B1:print('  ',t['t'],len(t['w']))
print('всего new_themes:',len(ex['new_themes']))
