"""Runtime fixes for Telegram editorial photo captions.

Goals:
- photo caption contains the post itself, not preview service text;
- generated images are not labelled with an internal AI-attribution line;
- every caption stays below Telegram's 1024-character limit without cutting
  a word/sentence in the middle;
- morning brief keeps weather, rail and roads even when the source draft is long.
"""
from __future__ import annotations

import re

import config
from utils import editorial_channel as editorial
from utils import editorial_overrides as overrides

CAPTION_LIMIT = 1024
POST_LIMIT = 900
MORNING_BODY_LIMIT = 820


def _is_ai_credit(value: str) -> bool:
    clean = (value or "").strip().lower()
    return clean.startswith("изображение создано ии") or clean.startswith("image generated by ai")


def _complete_cut(text: str, limit: int) -> str:
    """Cut only at a natural boundary; never leave a dangling half-sentence."""
    text = (text or "").strip()
    if len(text) <= limit:
        return text
    candidate = text[:limit].rstrip()
    # Prefer paragraph, then sentence boundary. Require it to be reasonably late.
    boundaries = [
        candidate.rfind("\n\n"),
        candidate.rfind(". "),
        candidate.rfind("! "),
        candidate.rfind("? "),
        candidate.rfind("… "),
    ]
    boundary = max(boundaries)
    if boundary >= int(limit * 0.62):
        end = boundary + (0 if candidate[boundary:boundary + 2] == "\n\n" else 1)
        return candidate[:end].rstrip()
    # Last resort: complete word, with ellipsis rather than a broken token.
    word = candidate.rfind(" ")
    return candidate[:word].rstrip(" ,;:-") + "…" if word > int(limit * 0.75) else candidate.rstrip() + "…"


def _fit_morning(text: str) -> str:
    """Keep headline + all three morning sections while shrinking verbose blocks."""
    clean = (text or "").strip()
    if len(clean) <= MORNING_BODY_LIMIT:
        return clean

    # Split by the three required emoji block markers while keeping their markers.
    matches = list(re.finditer(r"(?m)^(?=[☁️🌦️🌤️🌧️☀️🚆🚗])", clean))
    if len(matches) < 3:
        return _complete_cut(clean, MORNING_BODY_LIMIT)

    headline = clean[:matches[0].start()].strip()
    blocks: list[str] = []
    for i, match in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(clean)
        block = clean[match.start():end].strip()
        blocks.append(block)

    # Budget each factual block rather than letting rail disruptions consume all caption space.
    headline = _complete_cut(headline, 120)
    per_block = max(185, (MORNING_BODY_LIMIT - len(headline) - 8) // max(1, len(blocks)))
    fitted = [_complete_cut(block, per_block) for block in blocks[:3]]
    result = "\n\n".join(([headline] if headline else []) + fitted)
    return _complete_cut(result, MORNING_BODY_LIMIT)


def _fit_post(kind: str, text: str) -> str:
    return _fit_morning(text) if kind == "morning" else _complete_cut(text, 820)


# Preserve originals because the installer can be called more than once in tests.
_ORIGINAL_MORNING = editorial._morning_brief
_ORIGINAL_EVENT = editorial._event_spotlight
_ORIGINAL_CURIOSITY = editorial._curiosity_post
_ORIGINAL_EVENING = overrides._focused_evening_post


async def _short_morning() -> str | None:
    text = await _ORIGINAL_MORNING()
    return _fit_post("morning", text) if text else None


async def _short_event() -> str | None:
    text = await _ORIGINAL_EVENT()
    return _fit_post("event", text) if text else None


async def _short_curiosity() -> str | None:
    text = await _ORIGINAL_CURIOSITY()
    return _fit_post("curiosity", text) if text else None


async def _short_evening() -> str | None:
    text = await _ORIGINAL_EVENING()
    return _fit_post("evening", text) if text else None


def _caption(text: str, attribution: str = "") -> str:
    """Telegram photo caption: post + optional real-photo credit only."""
    credit = "" if _is_ai_credit(attribution) else (attribution or "").strip()
    suffix = f"\n\n{credit}" if credit else ""
    limit = CAPTION_LIMIT - len(suffix)
    body = _complete_cut(text, min(POST_LIMIT, limit))
    return body + suffix


async def _send_photo_preview(bot, admin_id: int, draft_id: str, kind: str, text: str, button: bool, image) -> bool:
    # The buttons already communicate that this is a preview. Do not waste caption
    # characters on service headers/footers: the preview must be pixel-identical to
    # what subscribers will read.
    credit = "" if _is_ai_credit(getattr(image, "attribution", "")) else getattr(image, "attribution", "")
    msg = await bot.send_photo(
        admin_id,
        photo=image.photo,
        caption=_caption(text, credit),
        parse_mode=None,
        reply_markup=editorial._approval_kb(draft_id),
    )
    if not msg.photo:
        return False
    await editorial._meta_set(f"ed_{draft_id}_photo", msg.photo[-1].file_id)
    await editorial._meta_set(f"ed_{draft_id}_credit", credit[:95])
    await editorial._meta_set(f"ed_{draft_id}_image_status", "ready")
    return True


def install_caption_patch() -> None:
    overrides._caption = _caption
    overrides._send_photo_preview = _send_photo_preview
    editorial._morning_brief = _short_morning
    editorial._event_spotlight = _short_event
    editorial._curiosity_post = _short_curiosity
    # Both scheduler and /editorialpreview must use the same shortened evening post.
    overrides._focused_evening_post = _short_evening
    editorial._evening_post = _short_evening


install_caption_patch()
