"""Editorial scheduling budget + manual photo choice.

Generation itself is owned only by editorial_verified_search. This module
controls retries, previews, manual photo generation, publication and a SAFE
health view that never spends Anthropic tokens.
"""
from __future__ import annotations

import os
from datetime import time
from importlib.metadata import PackageNotFoundError, version

from aiogram import F
from aiogram.types import CallbackQuery, InlineKeyboardButton, InlineKeyboardMarkup, Message

import config
from utils import editorial_channel as editorial
from utils import editorial_overrides as overrides
from utils.editorial_media import choose_editorial_image

EDITORIAL_MODEL = os.getenv("AI_EDITORIAL_MODEL", "claude-sonnet-5").strip() or "claude-sonnet-5"
try:
    _configured_searches = int(os.getenv("AI_EDITORIAL_WEB_MAX_USES", "2"))
except ValueError:
    _configured_searches = 2
EDITORIAL_WEB_MAX_USES = max(1, min(_configured_searches, 2))
MAX_AUTOMATIC_ATTEMPTS_PER_SLOT = 2
RETRY_MINUTES = 15
# Bump after a production generator fix so today's old failed attempts do not
# block the repaired runtime, while the new runtime still gets only two tries.
BUDGET_REVISION = "sonnet5-editorial-v4"


def _draft_choice_kb(draft_id: str) -> InlineKeyboardMarkup:
    return InlineKeyboardMarkup(inline_keyboard=[
        [
            InlineKeyboardButton(text="✅ Опубликовать без фото", callback_data=f"edpubtext:{draft_id}"),
            InlineKeyboardButton(text="🖼 Добавить фото", callback_data=f"edphoto:{draft_id}"),
        ],
        [InlineKeyboardButton(text="❌ Пропустить", callback_data=f"edskip:{draft_id}")],
    ])


def _photo_choice_kb(draft_id: str) -> InlineKeyboardMarkup:
    return InlineKeyboardMarkup(inline_keyboard=[
        [
            InlineKeyboardButton(text="✅ Опубликовать с фото", callback_data=f"edpub:{draft_id}"),
            InlineKeyboardButton(text="📝 Без фото", callback_data=f"edpubtext:{draft_id}"),
        ],
        [
            InlineKeyboardButton(text="🔄 Другое фото", callback_data=f"edretry:{draft_id}"),
            InlineKeyboardButton(text="❌ Пропустить", callback_data=f"edskip:{draft_id}"),
        ],
    ])


async def _text_first_send_for_approval(bot, kind: str, text: str, button: bool = False) -> bool:
    draft_id = overrides._new_draft_id()
    clean = text.strip()
    post_text = overrides._with_reaction_cta(kind, clean)
    await editorial._store_draft(draft_id, kind, post_text, button)
    await editorial._meta_set(f"ed_{draft_id}_image_status", "not_requested")

    sent = False
    labels = {
        "morning": "Утренний бриф",
        "event": "Мероприятие",
        "curiosity": "Познавательный пост",
        "evening": "Вечерний пост 21:00",
    }
    for admin_id in config.ADMIN_IDS:
        try:
            await bot.send_message(
                admin_id,
                f"👀 {labels.get(kind, kind)} · предпросмотр\n\n{post_text}\n\n"
                "Выберите, публиковать этот материал с фотографией или без неё.",
                parse_mode=None,
                reply_markup=_draft_choice_kb(draft_id),
                disable_web_page_preview=False,
            )
            sent = True
        except Exception as exc:  # noqa: BLE001
            editorial.log.warning("Cannot send editorial text-first preview: %s", exc)
    return sent


async def _send_selected_photo(bot, admin_id: int, draft_id: str, kind: str, text: str, button: bool, image) -> bool:
    credit = getattr(image, "attribution", "") or ""
    if credit.strip().lower().startswith(("изображение создано ии", "image generated by ai")):
        credit = ""
    msg = await bot.send_photo(
        admin_id,
        photo=image.photo,
        caption=overrides._caption(text, credit),
        parse_mode=None,
        reply_markup=_photo_choice_kb(draft_id),
    )
    if not msg.photo:
        return False
    await editorial._meta_set(f"ed_{draft_id}_photo", msg.photo[-1].file_id)
    await editorial._meta_set(f"ed_{draft_id}_credit", credit[:95])
    await editorial._meta_set(f"ed_{draft_id}_image_status", "ready")
    return True


async def _publish_text_only(callback: CallbackQuery) -> None:
    draft_id = callback.data.split(":", 1)[1]
    draft = await editorial._load_draft(draft_id)
    if not draft:
        await callback.answer("Этот черновик уже обработан", show_alert=True)
        return
    kind, text, button = draft
    try:
        await callback.bot.send_message(
            config.ANNOUNCE_CHANNEL,
            text,
            parse_mode=None,
            reply_markup=editorial._channel_kb() if button else None,
            disable_web_page_preview=False,
        )
        if kind in {"event", "curiosity", "evening"}:
            await editorial._remember_topic(text)
        await editorial._meta_set(f"ed_{draft_id}_status", "published")
        await callback.answer("Опубликовано без фото")
        await callback.message.edit_reply_markup(reply_markup=None)
    except Exception as exc:  # noqa: BLE001
        editorial.log.warning("Editorial text-only publish failed: %s", exc)
        await callback.answer("Не удалось опубликовать", show_alert=True)


@overrides.router.callback_query(F.data.startswith("edphoto:"), F.from_user.id.in_(config.ADMIN_IDS))
async def editorial_add_photo_callback(callback: CallbackQuery) -> None:
    draft_id = callback.data.split(":", 1)[1]
    draft = await editorial._load_draft(draft_id)
    if not draft:
        await callback.answer("Черновик уже обработан или недоступен", show_alert=True)
        return
    kind, text, button = draft
    await callback.answer("Создаю одно фото под главный сюжет…")
    await editorial._meta_set(f"ed_{draft_id}_image_status", "generating")
    image = await choose_editorial_image(text, kind)
    if not image:
        await editorial._meta_set(f"ed_{draft_id}_image_status", "failed")
        await callback.message.answer(
            "❌ Фото не удалось создать. Сам текст сохранён — его можно опубликовать без фото.",
            reply_markup=_draft_choice_kb(draft_id),
        )
        return
    try:
        await _send_selected_photo(callback.bot, callback.from_user.id, draft_id, kind, text, button, image)
        await callback.message.edit_reply_markup(reply_markup=None)
    except Exception as exc:  # noqa: BLE001
        editorial.log.warning("Selected photo preview failed: %s", exc)
        await callback.message.answer(
            f"❌ Фото получено, но Telegram не принял его: {type(exc).__name__}. Текст можно опубликовать без фото.",
            reply_markup=_draft_choice_kb(draft_id),
        )


@overrides.router.callback_query(F.data.startswith("edpubtext:"), F.from_user.id.in_(config.ADMIN_IDS))
async def editorial_publish_text_callback(callback: CallbackQuery) -> None:
    await _publish_text_only(callback)


def _anthropic_sdk_version() -> str:
    try:
        return version("anthropic")
    except PackageNotFoundError:
        return "не установлен"
    except Exception:
        return "неизвестно"


async def _safe_health(message: Message) -> None:
    if message.from_user.id not in config.ADMIN_IDS:
        return
    openai_ok, openai_detail = await overrides._check_openai_image_access()
    channel_ok, channel_detail = await overrides._channel_health(message.bot)
    last_status = await editorial._meta_get("editorial_last_status")
    last_error = await editorial._meta_get("editorial_last_error")
    lines = [
        "🩺 Editorial Health · SAFE",
        "",
        f"{'✅' if config.ANTHROPIC_API_KEY else '❌'} Anthropic key: {'задан' if config.ANTHROPIC_API_KEY else 'отсутствует'}",
        f"📦 Anthropic SDK: {_anthropic_sdk_version()}",
        f"{'✅' if config.AI_WEB_SEARCH else '❌'} Web Search: {'включён' if config.AI_WEB_SEARCH else 'выключен'}",
        f"🧠 Редакционная модель: {EDITORIAL_MODEL}",
        "🧠 Adaptive thinking: отключён для редакционных постов",
        f"🔎 Лимит Web Search на генерацию: {EDITORIAL_WEB_MAX_USES}",
        f"{'✅' if openai_ok else '❌'} OpenAI Images: {openai_detail}",
        f"{'✅' if channel_ok else '❌'} Канал/права: {channel_detail}",
        "",
        f"Последняя реальная генерация: {last_status or 'ещё нет после обновления'}",
    ]
    if last_error:
        lines.append(f"Последняя ошибка: {last_error}")
    lines.extend(["", "Команда не делает платный запрос к Anthropic."])
    await message.answer("\n".join(lines), parse_mode=None)


async def _alert_admins(bot, kind: str, reason: str) -> None:
    for admin_id in config.ADMIN_IDS:
        try:
            await bot.send_message(
                admin_id,
                f"⚠️ Не удалось подготовить {kind}. {reason}\n"
                f"Автоматический лимит: не более {MAX_AUTOMATIC_ATTEMPTS_PER_SLOT} попыток на слот в день.",
                parse_mode=None,
            )
        except Exception:
            pass


async def _budgeted_run_generated(bot, now, kind, date_key, generator, button=False):
    today = now.date().isoformat()
    if await editorial._meta_get(date_key) == today:
        return
    count_key = f"{date_key}_attempts_{BUDGET_REVISION}_{today}"
    cooldown_key = f"{date_key}_try_{BUDGET_REVISION}"
    try:
        attempts = int(await editorial._meta_get(count_key) or "0")
    except ValueError:
        attempts = 0
    if attempts >= MAX_AUTOMATIC_ATTEMPTS_PER_SLOT:
        return
    if not await editorial._attempt_allowed(cooldown_key, now, RETRY_MINUTES):
        return
    await editorial._meta_set(count_key, attempts + 1)
    try:
        text = await generator()
    except Exception as exc:  # noqa: BLE001
        editorial.log.exception("Budgeted %s generator crashed: %s", kind, exc)
        await _alert_admins(bot, kind, f"Ошибка {type(exc).__name__}.")
        return
    if not text:
        last_status = await editorial._meta_get("editorial_last_status")
        last_error = await editorial._meta_get("editorial_last_error")
        detail = f"Проверенный текст не получен. Диагностика: {last_status or 'unknown'}"
        if last_error:
            detail += f" · {last_error}"
        await _alert_admins(bot, kind, detail)
        return
    if await editorial._send_for_approval(bot, kind, text, button):
        await editorial._meta_set(date_key, today)


async def _budgeted_run_morning(bot, now):
    if time(6, 45) <= now.time() < time(9, 0):
        await _budgeted_run_generated(bot, now, "утренний бриф", "editorial_morning_date", editorial._morning_brief)


async def _budgeted_run_evening(bot, now):
    if time(21, 0) <= now.time() < time(23, 30):
        await _budgeted_run_generated(bot, now, "вечерний пост 21:00", "editorial_evening_date", editorial._evening_post)


def _replace_health_handler() -> None:
    try:
        for handler in overrides.router.message.handlers:
            callback = getattr(handler, "callback", None)
            if getattr(callback, "__name__", "") in {"editorial_health_command", "editorial_health_real"}:
                handler.callback = _safe_health
    except Exception as exc:  # noqa: BLE001
        editorial.log.warning("Could not install SAFE editorial health: %s", exc)


def install_editorial_budget_photo() -> None:
    editorial._send_for_approval = _text_first_send_for_approval
    overrides._photo_send_for_approval = _text_first_send_for_approval
    overrides._send_photo_preview = _send_selected_photo

    # Event and curiosity resolve editorial._run_generated dynamically, so this
    # replacement budgets all four formats together with morning/evening wrappers.
    editorial._run_generated = _budgeted_run_generated
    editorial._run_morning = _budgeted_run_morning
    editorial._run_evening = _budgeted_run_evening

    _replace_health_handler()
